### PR TITLE
feat(source): change to typescript

### PR DESCRIPTION
**Pull request by bluelovers**
https://github.com/ekalinin/sitemap.js/pull/180 @derduher

### CODE REVIEW

**Comment by derduher** [comment]
A couple of questions:
1. @ekalinin are you ok with converting to typescript?
2. why is this marked unsafe?
3. why does this contain both the ts version and the compiled js version? Why not have a build step rather than checking the code in?

**Comment by derduher** [comment]
Also, this looks like it was a lot of work. Thank you for your effort!

**Comment by bluelovers** [comment]
because i didn't have time change test script, and somehow i can't run test in local, that is why unsafe

.ts and .js is for if he didn't use ts, then still can use this .js for do test check

**Comment by derduher** [comment]
I'm seeing a merge conflict with index.js.
I can help with the tests
I think if we switch to typescript we'll want to remove the js and just generate it pre-publish rather than check in the generated code.

**Comment by bluelovers** [comment]
```
$ jasmine tests/sitemap.test.js
Randomized with seed 36106
Started
.............................................................................


77 specs, 0 failures
Finished in 0.138 seconds
Randomized with seed 36106 (jasmine --random=true --seed=36106)
Done in 0.54s.

```

**Comment by ekalinin** [comment]
Hey guys!

Thank you so much for your effort!
I definitely going to apply this PR, but a little bit busy at the moment.
Sorry for delay.

**Comment by derduher** [comment]
No worries, I've been debating asking if you wanted to set up a team of
maintainers so it wouldn't have to all be on you. And selfishly so I could
get my PRs merged faster :D.

**Comment by ekalinin** [comment]
> I've been debating asking if you wanted to set up a team of
> maintainers so it wouldn't have to all be on you. And selfishly so I could
> get my PRs merged faster :D.

Yeah, good point :) Just sent you an invite.

**Comment by derduher** [comment]
@ekalinin Thanks! I'll see if I can clear out the PR backlog and then I'll message you to cut an npm release.

**Comment by derduher** [comment]
@ekalinin PRs merged and a version tagged. Can you do an npm release?

**Comment by ekalinin** [comment]
@derduher 

>  PRs merged and a version tagged.

That's great! Thank you very much!

> Can you do an npm release?

Done: https://www.npmjs.com/package/sitemap/v/3.0.0

**Pull request merged**
