### PR TITLE
Added image option

### PR DESCRIPTION
**Pull request by sidneyvav**
Just add the img on urls's JSON with the img url

### CODE REVIEW

**Comment by ekalinin** [comment]
Thanks for PR. Seems it will suite for #13.
But would you be able to add some tests?

**Comment by ekalinin** [comment]
As far as i can see, the only commit that make sense is f5199da. Right?

**Comment by sidneyvav** [comment]
Yes, the other ones are because I reorginized the struct of the file, but it was a mistake

**Comment by ekalinin** [comment]
Thank you very much!
Will wait your tests.

**Comment by sidneyvav** [comment]
I updated the tests file but I couldn't execute it. So I'm not sure if it's exactly right.

**Comment by ekalinin** [comment]
Merged:
  * https://github.com/ekalinin/sitemap.js/compare/f88d949315...master

**Pull request closed without merging**
