### PR TITLE
Use HTTPS instead of HTTP

### PR DESCRIPTION
**Pull request by TimoRuetten**
Use https protocol instead of http. I don't know if HTTP this will cause problems with google or other search engines. But google chrome seems to have problems with displaying this XML sitemap when the protocol is not HTTPS so I changed it and it worked great again.

### CODE REVIEW

**Comment by ekalinin** [comment]
@TimoRuetten Thanks for the patch!

Could you fix test, please.

**Comment by knoxcard** [comment]
Any update?

**Comment by TimoRuetten** [comment]
Oh, sorry. Did not see that the tests failed. I will check it later this day or tomorrow and will fix it.

**Comment by ekalinin** [comment]
@TimoRuetten any updates?

**Pull request closed without merging**
