### PR TITLE
release v4

### PR DESCRIPTION
**Pull request by derduher**
# 4.0.0

This release is geared around overhauling the public api for this library. Many 
options have been introduced over the years and this has lead to some inconsistencies
that make the library hard to use. Most have been cleaned up but a couple notable
items remain, including the confusing names of buildSitemapIndex and createSitemapIndex

  - A new experimental CLI
    - stream in a list of urls stream out xml
    - validate your generated sitemap
  - Sitemap video item now supports id element
  - Several schema errors have been cleaned up.
  - Docs have been updated and streamlined.
## breaking changes
  - lastmod option parses all ISO8601 date-only strings as being in UTC rather than local time
    - lastmodISO is deprecated as it is equivalent to lastmod
    - lastmodfile now includes the file's time as well
    - lastmodrealtime is no longer necessary
  - The default export of sitemap lib is now just createSitemap
  - Sitemap constructor now uses a object for its constructor
  ```
    const { Sitemap } = require('sitemap');
    const siteMap = new Sitemap({
      urls = [],
      hostname: 'https://example.com', // optional
      cacheTime = 0,
      xslUrl,
      xmlNs,
      level = 'warn'
    })
  ```
  - Sitemap no longer accepts a single string for its url
  - Drop support for node 6
  - Remove callback on toXML - This had no performance benefit
  - Direct modification of urls property on Sitemap has been dropped. Use add/remove/contains
  - When a Sitemap item is generated with invalid options it no longer throws by default
    - instead it console warns.
    - if you'd like to pre-verify your data the `validateSMIOptions` function is
    now available
    - To get the previous behavior pass level `createSitemap({...otheropts, level: 'throw' }) // ErrorLevel.THROW for TS users`
#215 has all the changes

### CODE REVIEW

**Comment by derduher** [comment]
@ekalinin can you cut a new release?

**Comment by ekalinin** [comment]
Hey!

Thank you for your efforts!
I would like to cut a new release but i see some failed tests:

```
➜ npm run test

 PASS  tests/sitemap-shape.test.ts
 PASS  tests/sitemap-item.test.ts
(node:17895) UnhandledPromiseRejectionWarning: [object Array]
(node:17895) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17895) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  tests/xmllint.test.ts
  ● xmllint › resolves when complete

    expect.assertions(1)

    Expected one assertion to be called but received zero assertion calls.

       9 | 
      10 |   it('resolves when complete', async () => {
    > 11 |     expect.assertions(1)
         |            ^
      12 |     try {
      13 |       await expect(xmlLint('./tests/cli-urls.json.xml')).resolves.toBeFalsy()
      14 |     } catch (e) {

      at assertions (tests/xmllint.test.ts:11:12)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at asyncGeneratorStep (tests/xmllint.test.ts:7:103)
      at _next (tests/xmllint.test.ts:9:194)
      at tests/xmllint.test.ts:9:364
      at Object.<anonymous> (tests/xmllint.test.ts:9:97)

 PASS  tests/sitemap-index.test.ts
 PASS  tests/sitemap.test.ts
 FAIL  tests/cli.test.ts (31.306s)
  ● Console

    console.log tests/cli.test.ts:50
      JestAssertionError: expect(received).toBe(expected) // Object.is equality
      
      - Expected
      + Received
      
      - valid
      + 
        
          at toBe (/home/kev/projects/my/sitemap.js/tests/cli.test.ts:48:22)
          at processTicksAndRejections (internal/process/task_queues.js:85:5) {
        matcherResult: {
          actual: '\n',
          expected: 'valid\n',
          message: [Function],
          name: 'toBe',
          pass: false
        }
      }

  ● cli › validates xml piped in

    Command failed: node ./dist/cli.js --validate < ./tests/cli-urls.json.xml
    CLI is in new and likely to change quite a bit. Please send feature/bug requests to https://github.com/ekalinin/sitemap.js/issues
    events.js:180
          throw er; // Unhandled 'error' event
          ^

    Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

      at internal/fs/streams.js:197:12
      Emitted 'error' event at:

  ● cli › validates xml specified as file

    Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error: 

      44 |   }, 30000)
      45 | 
    > 46 |   it('validates xml specified as file', (done) => {
         |   ^
      47 |     exec('node ./dist/cli.js --validate ./tests/cli-urls.json.xml', {encoding: 'utf8'}).then(({stdout, stderr}) => {
      48 |       expect(stdout).toBe('valid\n')
      49 |       done()

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (tests/cli.test.ts:46:3)
      at Object.describe (tests/cli.test.ts:13:1)

------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    93.78 |    88.62 |    94.64 |    93.77 |                   |
 errors.ts        |    90.91 |       90 |    90.91 |    90.91 |          87,88,90 |
 sitemap-index.ts |    94.55 |    81.82 |      100 |    94.55 |       137,148,177 |
 sitemap-item.ts  |    97.78 |    94.21 |       90 |    97.78 |          29,91,92 |
 sitemap.ts       |    99.03 |      100 |       95 |    99.02 |               140 |
 types.ts         |      100 |      100 |      100 |      100 |                   |
 utils.ts         |    77.78 |    80.72 |      100 |    77.78 |... 32,134,146,174 |
 xmllint.ts       |    91.67 |    53.85 |      100 |    91.67 |                19 |
------------------|----------|----------|----------|----------|-------------------|
Test Suites: 2 failed, 4 passed, 6 total
Tests:       3 failed, 104 passed, 107 total
Snapshots:   0 total
Time:        32.139s

```

**Comment by derduher** [comment]
Ah well good thing there are tests to prevent its release then. I had assumed xmlLint was nearly everywhere. I'll throw in a check then for it and ping you again when thats there.

**Comment by derduher** [comment]
@ekalinin give it another try. I've tagged 4.0.1 with some changes that will skip xmllint if you don't have it.

**Comment by ekalinin** [comment]
Great! Thanks!
Done:
- https://www.npmjs.com/package/sitemap/v/4.0.1

**Pull request merged**
