### PR TITLE
Add support for image:caption

### PR DESCRIPTION
**Pull request by nguyenngocphuongnb**
Usage:
sitemap.add({
	url: '/sample-url/,
	changefreq: 'weekly',
	priority: 0.6,
	lastmod: timestamp(),
	img: {
		url: '/image-url.jpg',
		caption: 'Caption for image'
	}
});

or

sitemap.add({
	url: '/sample-url/,
	changefreq: 'weekly',
	priority: 0.6,
	lastmod: timestamp(),
	img: [
		{
			url: '/image-url.jpg',
			caption: 'Caption for image'
		},
		{
			url: '/other-image-url.jpg',
			caption: 'Caption for other image'
		},
	]
});

### CODE REVIEW

**Comment by ekalinin** [comment]
Hey @nguyenngocphuongnb 

Thanks for the patch!
But would you be able to:
  * revert back original comments/formatting (currently it's difficult to analyze the diff)
  * add some tests
?

**Comment by nguyenngocphuongnb** [comment]
thank you, i will revert back to original comments and formatting. The reason is that phpstorm auto format code when paste to editor

**Comment by daedlock** [comment]
@ekalinin please get this merged

**Comment by rauberdaniel** [comment]
@daedlock I think the issue here is still that it changes all the formatting. This should be fixed by @nguyenngocphuongnb before merging.

**Comment by daedlock** [comment]
Its been 3 month and I would love to see this feature because its common now that a sitemap will have image links. I can write another patch if thats ok with you

**Comment by rauberdaniel** [comment]
@daedlock Images are already supported, just captions aren’t. I am already working on a PR which I will submit in a few hours.

**Comment by rauberdaniel** [comment]
Alright, I opened #77 which includes this feature update, tests and an example.

**Comment by ekalinin** [comment]
Thanks @rauberdaniel !

**Pull request closed without merging**
