### PR TITLE
release 4.1.0

### PR DESCRIPTION
**Pull request by derduher**
Add a pretty print option to toString(false) pass true pretty print #230 

[Add an xmlparser](https://github.com/ekalinin/sitemap.js/pull/232) that will output a config that would generate that same file 

cli: use --parser to output the complete config --line-separated to print out line separated config compatible with the --json input option for cli

 lib: import parseSitemap and pass it a stream

### CODE REVIEW

**Comment by derduher** [comment]
@ekalinin Can you do another release? Thanks in advance!

**Comment by derduher** [comment]
This is actually now 4.1.1 as I forgot to include a dependency in the original.

**Comment by ekalinin** [comment]
> Can you do another release? Thanks in advance!

@derduher done:

- https://www.npmjs.com/package/sitemap/v/4.1.1

Thank you so much!

**Comment by okaris** [comment]
Hi, I saw a mention of inputting a stream of urls and getting an output stream of the xmls? I have a lot of urls to be parted in sitemap files by 5k/10k. Does this library support this kind of usage? Without streaming there are memory limitations. Thank you

**Comment by derduher** [comment]
@okaris the cli supports that now. The library has it planned but for now you can get it working by 
stitching some of the elements together like so.

import { SitemapItem, Sitemap } from 'sitemap'
normalizedURL = Sitemap.normalizeURL(url/config)
stream.write(SitemapItem.justItem(normalizedURL))

**Comment by derduher** [comment]
if you are asking about the CLI `npx sitemap < listofurls.txt > sitemap.xml` running that will stream.

**Comment by derduher** [comment]
@okaris I put together an alpha streaming interface in #243. It runs so much better I'm thinking of pushing most users to it. Feel free to comment. I still have some work to do before I merge and release it.
I would love to know from you how you would like to stream in your URLs? Are you pulling it from a file? pulling from a database? I want to try and cover your use-case in the documentation.

**Comment by okaris** [comment]
Hi @derduher thank you for all the information. I have a big list of products and their urls in a database. If I fetch them all at once the process uses a lot of memory. Both for the initial list and then probably for the object that holds the sitemap data. I was planning to use Mongo's streaming option to pipe the urls to the sitemap module.

**Pull request merged**
