### PR TITLE
Improve normalizeURL performance

### PR DESCRIPTION
**Pull request by mohd-akram**
This also fixes the input object being modified by the function.

We avoid double iteration when processing an image list, and an unnecessary copy of the sitemap item object.

Also, ensure we return early when only a URL is given. This significantly improves performance in the `stream-2` perf test:

Before:

```
runs: 1 batches: 1 total: 1
testing lots of data
========= stream-2 =============
median: 13994.0±0.0ms
99th percentile: 13994.0ms
```

After:

```
runs: 1 batches: 1 total: 1
testing lots of data
========= stream-2 =============
median: 5575.0±0.0ms
99th percentile: 5575.0ms
```

Other benchmarks also see improvement:

Before:

```
runs: 10 batches: 10 total: 100
testing stream
========= stream =============
median: 1218.0±63.0ms
99th percentile: 1448.0ms
```

After:

```
runs: 10 batches: 10 total: 100
testing stream
========= stream =============
median: 1071.5±66.6ms
99th percentile: 1387.0ms
```

Use the "Hide whitespace" option in GitHub for clarity while reviewing.

### CODE REVIEW

**Comment by huntharo** [comment]
@mohd-akram - Thanks for the contribution!

Can you edit the summary with *why* the changes improve performance such as "eliminates date objects are being created and destroyed without being changed" or something to that effect?

Also, can you quantify at all the performance benefit on hundreds of thousands of items being written to files or to memory streams?  Is it 0.1% time reduction or 10% time reduction?  Any impact on memory usage or GC times?

**Comment by mohd-akram** [comment]
@huntharo Thanks for looking at this. I've added some more information in the description. There's no change in memory usage or GC times that I could find, there might a small improvement due reducing a copy, but not really the focus of the PR.

**Review by huntharo — APPROVED** [review]
@derduher - I think this one is good to go!

I have reviewed the code.  It's well covered by tests and all the tests are passing.  In the best cases (using logs of images, videos, links) it's reducing runtime by 50%.  In other cases it's reducing runtime and memory usage by about 10-20%.

This is a fantastic improvement!

## CoPilot Review Notes - Additional Context

The new version of the function is faster and more memory efficient due to several reasons:

- Less object manipulation: The new version avoids unnecessary object creation and manipulation. For example, in the old version, `smiLoose.img` is reassigned multiple times, each time creating a new array or object. In the new version, `smi.img` is assigned only once, and the array is created directly in the assignment.

- Less conditional checks: The new version has fewer conditional checks, which can slow down execution. For example, the old version checks if `(typeof smiLoose.img === 'string')` and `if (!Array.isArray(smiLoose.img))` separately, while the new version combines these checks into one `if (img)` statement.

- Direct assignment: The new version uses direct assignment `(smi.url = new URL(url, hostname).toString();)` instead of spreading properties from one object to another `(smi = { ...smiLoose, ...smi };)`. This is faster and uses less memory because it avoids creating a new object.

**Comment by derduher** [comment]
Thanks @mohd-akram

**Comment by derduher** [comment]
I'll note that I don't see the perf improvement on node 22 but do see it on the previous versions. Not sure what that's about.

**Pull request merged**
