### PR TITLE
Ignore package-lock.json

### PR DESCRIPTION
**Pull request by realityking**
For libraries, it's better not to have the `package-lock.json` in the repo to make sure tests always run with the newest in-range version of all dependencies.

### CODE REVIEW

**Comment by realityking** [comment]
The package-lock.json is only used when directlynindtalling the package, not when it’s installed as a dependency.

This means if an in-range dependencie breaks if wouldn’t show in local dev or on CI, only consumers would notice.

**Comment by derduher** [comment]
makes sense 👍

**Comment by realityking** [comment]
Rebased & fixed the merge conflict

**Comment by ekalinin** [comment]
Thanks!

**Pull request merged**
