### PR TITLE
Expires tag addition for Google on-demand indexation removal.

### PR DESCRIPTION
**Pull request by Mickael-van-der-Beek**

### CODE REVIEW

**Comment by ekalinin** [comment]
Thanks!

**Comment by Mickael-van-der-Beek** [comment]
@ekalinin Hi, I was just wondering if it would be possible to push to NPM a new version of sitemap.js containing this PR?

**Comment by ekalinin** [comment]
@Mickael-van-der-Beek Hey, done:
  * https://github.com/ekalinin/sitemap.js/releases/tag/1.10.1

**Comment by Mickael-van-der-Beek** [comment]
@ekalinin Awesome! Thank you very much.

**Pull request merged**
