### PR TITLE
Issue-423 - Propagate errors in `SitemapAndIndexStream`

### LINKED ISSUE #423: [ BUG ] `SitemapAndIndexStream` hangs on end if `SitemapStream` encountered error writing to its destination
**Describe the bug**

When `SitemapStream` gets an error writing to its destination stream, such as when the file cannot be created, `SitemapAndIndexStream` will hang on `.end()` / `await finished()` and the error will not propagate back to the caller.

**Expected behavior**
- `SitemapAndIndexStream` should propagate the error encountered by the `SitemapStream`
- `SitemapAndIndexStream` should not hang when `.end()`/ `await finished()` are called

**Context:**
 - Library Version 7.1.1

**Additional context**

Will provide a failing test.

### PR DESCRIPTION
**Pull request by huntharo**
Fixes #423

### CODE REVIEW

**Comment by huntharo** [comment]
@derduher - We have a choice here.  We can merge this to show the isolated test / fix OR we can merge a larger fix that addresses other issues with `SitemapAndIndexStream` and is easier to understand / maintain.

**Comment by derduher** [comment]
@huntharo I'm about to release a version that will be the last before a breaking change that drops support for node < 18. So if you have a preference now is the time to voice it :)

**Comment by huntharo** [comment]
> @huntharo I'm about to release a version that will be the last before a breaking change that drops support for node < 18. So if you have a preference now is the time to voice it :)

We should probably get these changes out before the node 12, 14, 16 drop.

**Comment by huntharo** [comment]
@derduher You can proceed with dropping Node 12 support.  The stream handling in Node 12 is pretty bad so one of the tests fails with Node 12 and can't be made to work.

**Comment by derduher** [comment]
I'm still reviewing this but in running `npm run test:perf -- 3 3 stream true` This MR has dropped peak memory usage by 1000x. from 78mb to 78kb. I had to modify the script to drop down a unit.

**Comment by derduher** [comment]
@huntharo thank you! Also be sure to see my comment above about the improved memory performance.

**Comment by huntharo** [comment]
> npm run test:perf -- 3 3 stream true

Hmm... I'm running that test but I'm not seeing a change in memory usage?

**Comment by derduher** [comment]
yeah I think you are right. After merging the improvement in memory is gone. 🤷

**Comment by huntharo** [comment]
```sh
 npm run test:perf -- 3 3 stream true     

> sitemap@9.0.0 test:perf
> node ./tests/perf.js 3 3 stream true

npm run test:perf -- [number of runs = 10] [batch size = 10] [stream(default)|combined] [measure peak memory = false]
runs: 3 batches: 3 total: 9
testing stream
========= stream =============
median: 0.0±0.0mb
99th percentile: 0.0mb
```

Now I'm getting the improvement, for the first time that I have observed.  We should try to figure out what is going on here.

**Comment by huntharo** [comment]
Added #436 - The change is due to Node v18 -> v20... not due to any code change.  Not sure yet if it is a change in memory reporting or a change in memory use.

**Pull request merged**
